### ISSUE TITLE
Keep session on refresh

### ISSUE THREAD

**Issue by iamricard** [cloudspace/angular_devise#17]
When the user does a hard refresh (F5), the session is "lost". Would it be a good idea to add an option to store the session with ngCookie? Bare in mind I'm getting started with Angular and I might be doing things wrong, so it really is just a question.

**edit**: The other solution is probably just run `Auth.currentUser()` on the `.run` on Angular, but I would like to know your opinion on the matter. I hope I'm not bothering you guys too much.

**Comment by loureirorg** [comment]
Just a few tips for Angular + Devise beginners:

**1. install [rack-cors gem](https://github.com/cyu/rack-cors)**
```ruby
# Gemfile
gem 'rack-cors', :require => 'rack/cors'
```
```ruby
# application.rb
config.middleware.insert_before 0, "Rack::Cors" do
  allow do
    origins '*'
    resource '*', :headers => :any, :methods => [:get, :post, :delete, :put, :head]
  end
end    
```
**PS:** *don't put an ":options". If you do that, you won't be able to destroy sessions, because Angular will replace "delete" by "options" when communicating with another domain (and Devise won't recognize the "option" verb as a "delete")*
**PS II:** *don't forget to restart the server!!!*

**2. at your "config" (on Angular):**
```js
$httpProvider.defaults.withCredentials = true;
```
or a more extensive example:
```js
angular.module('myModule', ['Devise'])
  .config(function(AuthProvider, $httpProvider) {
    $httpProvider.defaults.withCredentials = true;
  });
```

**3. remove the CSRF protection from Rails (I know, I know...)**
```ruby
# application_controller.rb
# protect_from_forgery
```
**PS:** *after do some tests and all it's working, you can use a better solution to deal with CSRF, like use [this angular_rails_csrf gem](https://github.com/jsanders/angular_rails_csrf) (which doesn't worked for me, but maybe you have more luck).*
**PS II:** *"I don't recommend to disable CSRF protection, blah, blah, blah..." Yeah, me neither, it's just a test in order to troubleshooting why sessions are being lost after a refresh.*

**4. after a refresh, get the session back**
```js
angular.module('myModule', ['Devise'])
  .run(['Auth', function (Auth) {
    Auth.currentUser().then(function(user) {
      console.log(user);
      console.log(Auth._currentUser);
    });
  }]);
```

**Comment by alediniz** [comment]
Thanks very much **loureirorg**
